services:
  dc_blog:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: blog-dev-container:latest
    container_name: blog-dev-container
    ports:
      - 4321-4400:4321-4400
      - 6006-6100:6006-6100
    volumes:
      - ..:/app:cached
      - ./.home:/home/dev/
    working_dir: /app
    user: dev
    tty: true
    stdin_open: true
    command: sleep infinity
