services:
  dc_blog:
    build:
      context: .
      dockerfile: Dockerfile
    image: blog-dev-container:latest
    container_name: blog-dev-container
    ports:
      - 4321-4400:4321-4400
      - 6006-6100:6006-6100
    volumes:
      - ..:/workspace:cached
      - ./.home:/home/vscode/
    working_dir: /workspace
    user: vscode
    tty: true
    stdin_open: true
    command: sleep infinity
